#pragma once

#include <graphics/core/pointers/EntityPtr.h>
#include <string>

/**
 * Loads model files generated by third-party tools into renderable TitanForge meshes
 * @author Nathaniel Rex
 */
class ModelLoader
{
public:

	/**
	 * Loads a model and converts its node hierarchy into TitanForge entities that can be rendered
	 * @param path Path to the model, relative to the running executable
	 * @return An entity group corresponding to the imported scene's root node
	 * @throws InstantiationException on failure to import the entity
	 */
	static EntityPtr load(const std::string& path);
};
